export const SET_ENABLED_ADS = 'SET_ENABLED_ADS'
export const FIREBASE_UPDATE_ADS_REQUESTING = 'FIREBASE_UPDATE_ADS_REQUESTING'
export const FIREBASE_UPADTE_ADS_FAILED = 'FIREBASE_UPADTE_ADS_FAILED'
export const FIREBASE_UPADTE_ADS_RECEIVING = 'FIREBASE_UPADTE_ADS_RECEIVING'