target 'BattleBuddy' do

  platform :ios, '12.2'

  use_frameworks!

  inhibit_all_warnings!

  pod 'Alamofire', '~> 4.8.2'
  pod 'SDWebImage', '~> 5.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/AdMob'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/Firestore'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.4'
  pod 'JGProgressHUD'
  pod "youtube-ios-player-helper", "~> 0.1.4"
end
